version: "2.1"
services:
  registryproxy:
    image: registry:2
    ports:
     - "5005:5000"
    restart: always
    volumes:
     - /DockerVolumes/regData:/var/lib/registry
    environment:
     - REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io
    networks:
      - infraNet
  registry:
    image: registry:2
    ports:
     - "5000:5000"
    restart: always
    depends_on:
     - registryproxy
    volumes:
     - /DockerVolumes/registryData:/var/lib/registry
    networks:
      - infraNet
networks:
  infraNet: